package com.mycompany.desafiogg.src.view;

import com.mycompany.desafiogg.src.controller.ContaController;
import com.mycompany.desafiogg.src.controller.ReceitaController;
import com.mycompany.desafiogg.src.model.Banco;
import com.mycompany.desafiogg.src.model.Conta;
import javax.swing.JOptionPane;

public class View extends javax.swing.JFrame {
    
    private Banco banco;
    private ContaController contaController;
    private ReceitaController receitaController;

    /**
     * Creates new form Dashboard
     */
    public View() {
        initComponents();
        
         jComboBoxContasEditarConta.addItemListener(event -> {
            // The item affected by the event.
            String item = (String) event.getItem();
            this.setContaInEditView(item);
        });
    }
    
    public void setContaInEditView(String codigoConta) {
        Conta conta = this.banco.getConta(codigoConta);
        
        if (conta == null) {
            JOptionPane.showMessageDialog(null, "Não foi possível encontrar a conta!");
        }
        jTextFieldContasEditarCpf.setText(conta.getCpfTitular());
        jTextFieldContasEditarTitular.setText(conta.getTitular());
        jTextFieldContasEditarSaldo.setText(conta.getSaldo()+"");
    }
    
    public void setBanco(Banco banco) {
        this.banco = banco;
    }
    
    public void setContaController(ContaController controller) {
        this.contaController = controller;
    }

    public void setReceitaController(ReceitaController controller) {
        this.receitaController = controller;
    }
    
    private void limparCadastroConta() {
        jTextFieldContasCadastrarCpf.setText("");
        jTextFieldContasCadastrarTitular.setText("");
    }
    
    private void limparCadastroReceita() {
        jTextFieldReceitasCadastroDataRecebimento.setText("");
        jTextFieldReceitasCadastroDataRecebimentoEsperado.setText("");
        jTextFieldReceitasCadastroDescricao.setText("");
        jTextFieldReceitasCadastroValor.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jTextFieldContasCadastrarTitular = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldContasCadastrarCpf = new javax.swing.JTextField();
        jButtonSalvarConta = new javax.swing.JButton();
        jButtonLimparCadastroConta = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldContasEditarTitular = new javax.swing.JTextField();
        jTextFieldContasEditarCpf = new javax.swing.JTextField();
        jButtonAtualizarConta = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxContasEditarConta = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldContasEditarSaldo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButtonReceitasSalvar = new javax.swing.JButton();
        jTextFieldReceitasCadastroValor = new javax.swing.JTextField();
        jTextFieldReceitasCadastroDataRecebimento = new javax.swing.JTextField();
        jTextFieldReceitasCadastroDataRecebimentoEsperado = new javax.swing.JTextField();
        jTextFieldReceitasCadastroDescricao = new javax.swing.JTextField();
        jButtonReceitasCadastroLimpar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxReceitasCadastroConta = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxReceitasEdicaoReceita = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldReceitasEdicaoValor = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldReceitasEdicaoDataRecebimento = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldReceitasCadastroDataEdicaoEsperado = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldReceitasEdicaoDescricao = new javax.swing.JTextField();
        jButtonReceitasSalvar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane2.setToolTipText("");
        jTabbedPane2.setVerifyInputWhenFocusTarget(false);

        jLabel1.setText("Titular");

        jLabel2.setText("CPF");

        jButtonSalvarConta.setText("Salvar");
        jButtonSalvarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarContaActionPerformed(evt);
            }
        });

        jButtonLimparCadastroConta.setText("Limpar");
        jButtonLimparCadastroConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparCadastroContaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButtonLimparCadastroConta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSalvarConta))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jTextFieldContasCadastrarTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldContasCadastrarCpf)))))
                .addContainerGap(346, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldContasCadastrarTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldContasCadastrarCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvarConta)
                    .addComponent(jButtonLimparCadastroConta))
                .addContainerGap(335, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Cadastrar", jPanel4);

        jLabel3.setText("Titular");

        jLabel4.setText("CPF");

        jButtonAtualizarConta.setText("Atualizar Conta");
        jButtonAtualizarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarContaActionPerformed(evt);
            }
        });

        jLabel5.setText("Conta");

        jComboBoxContasEditarConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBoxContasEditarContaMousePressed(evt);
            }
        });
        jComboBoxContasEditarConta.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jComboBoxContasEditarContaComponentShown(evt);
            }
        });

        jLabel6.setText("Saldo");

        jTextFieldContasEditarSaldo.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonAtualizarConta)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBoxContasEditarConta, 0, 128, Short.MAX_VALUE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel6))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldContasEditarTitular)
                                .addComponent(jTextFieldContasEditarCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                .addComponent(jTextFieldContasEditarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(360, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxContasEditarConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldContasEditarTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldContasEditarCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldContasEditarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jButtonAtualizarConta)
                .addContainerGap(265, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Editar", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jTabbedPane2.getAccessibleContext().setAccessibleName("Cadastrar/Editar");

        jTabbedPane1.addTab("Contas", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Despesas", jPanel2);

        jLabel7.setText("valor");

        jLabel8.setText("Data Recebimento");

        jLabel9.setText("Data Recebimento Esperado");

        jLabel10.setText("descrição");

        jButtonReceitasSalvar.setText("Salvar");
        jButtonReceitasSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReceitasSalvarActionPerformed(evt);
            }
        });

        jTextFieldReceitasCadastroDataRecebimentoEsperado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldReceitasCadastroDataRecebimentoEsperadoActionPerformed(evt);
            }
        });

        jButtonReceitasCadastroLimpar.setText("Limpar");
        jButtonReceitasCadastroLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReceitasCadastroLimparActionPerformed(evt);
            }
        });

        jLabel11.setText("Conta");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jButtonReceitasCadastroLimpar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonReceitasSalvar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldReceitasCadastroValor)
                            .addComponent(jTextFieldReceitasCadastroDataRecebimento)
                            .addComponent(jTextFieldReceitasCadastroDataRecebimentoEsperado)
                            .addComponent(jTextFieldReceitasCadastroDescricao)
                            .addComponent(jComboBoxReceitasCadastroConta, 0, 101, Short.MAX_VALUE))))
                .addContainerGap(299, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBoxReceitasCadastroConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldReceitasCadastroValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldReceitasCadastroDataRecebimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldReceitasCadastroDataRecebimentoEsperado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldReceitasCadastroDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonReceitasSalvar)
                    .addComponent(jButtonReceitasCadastroLimpar))
                .addContainerGap(207, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Cadastro", jPanel6);

        jLabel12.setText("Receita");

        jLabel13.setText("valor");

        jLabel14.setText("Data Recebimento");

        jLabel15.setText("Data Recebimento Esperado");

        jTextFieldReceitasCadastroDataEdicaoEsperado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldReceitasCadastroDataEdicaoEsperadoActionPerformed(evt);
            }
        });

        jLabel16.setText("descrição");

        jButtonReceitasSalvar1.setText("Atualizar");
        jButtonReceitasSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReceitasSalvar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonReceitasSalvar1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldReceitasEdicaoValor)
                            .addComponent(jTextFieldReceitasEdicaoDataRecebimento)
                            .addComponent(jTextFieldReceitasCadastroDataEdicaoEsperado)
                            .addComponent(jTextFieldReceitasEdicaoDescricao)
                            .addComponent(jComboBoxReceitasEdicaoReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(288, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jComboBoxReceitasEdicaoReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldReceitasEdicaoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldReceitasEdicaoDataRecebimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldReceitasCadastroDataEdicaoEsperado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldReceitasEdicaoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jButtonReceitasSalvar1)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Edicao", jPanel7);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );

        jTabbedPane1.addTab("Receitas", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarContaActionPerformed
        this.contaController.cadastrarConta(
                jTextFieldContasCadastrarTitular.getText(), 
                jTextFieldContasCadastrarCpf.getText()
        );
        jComboBoxContasEditarConta.addItem(this.banco.getNumeroContasRegistradas()+"");
        jComboBoxReceitasCadastroConta.addItem(jTextFieldContasCadastrarTitular.getText());
        
        JOptionPane.showMessageDialog(null, "Conta cadastrada com sucesso!");
        
        this.limparCadastroConta();
        
    }//GEN-LAST:event_jButtonSalvarContaActionPerformed

    private void jButtonLimparCadastroContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparCadastroContaActionPerformed
        // TODO add your handling code here:
        this.limparCadastroConta();
    }//GEN-LAST:event_jButtonLimparCadastroContaActionPerformed

    private void jComboBoxContasEditarContaComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jComboBoxContasEditarContaComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxContasEditarContaComponentShown

    private void jComboBoxContasEditarContaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxContasEditarContaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxContasEditarContaMousePressed

    private void jButtonAtualizarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarContaActionPerformed
        int codigoConta = jComboBoxContasEditarConta.getSelectedIndex()+1;
        Conta conta = this.banco.getConta(codigoConta);
        conta.setCpfTitular(jTextFieldContasEditarCpf.getText());
        conta.setTitular(jTextFieldContasEditarTitular.getText());
        
        JOptionPane.showMessageDialog(null, "Atualizada conta " + codigoConta + " com sucesso!");
    }//GEN-LAST:event_jButtonAtualizarContaActionPerformed

    private void jTextFieldReceitasCadastroDataRecebimentoEsperadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldReceitasCadastroDataRecebimentoEsperadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldReceitasCadastroDataRecebimentoEsperadoActionPerformed

    private void jButtonReceitasCadastroLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReceitasCadastroLimparActionPerformed
        // TODO add your handling code here:
        this.limparCadastroReceita();
    }//GEN-LAST:event_jButtonReceitasCadastroLimparActionPerformed

    private void jButtonReceitasSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReceitasSalvarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonReceitasSalvarActionPerformed

    private void jTextFieldReceitasCadastroDataEdicaoEsperadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldReceitasCadastroDataEdicaoEsperadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldReceitasCadastroDataEdicaoEsperadoActionPerformed

    private void jButtonReceitasSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReceitasSalvar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReceitasSalvar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizarConta;
    private javax.swing.JButton jButtonLimparCadastroConta;
    private javax.swing.JButton jButtonReceitasCadastroLimpar;
    private javax.swing.JButton jButtonReceitasSalvar;
    private javax.swing.JButton jButtonReceitasSalvar1;
    private javax.swing.JButton jButtonSalvarConta;
    private javax.swing.JComboBox<String> jComboBoxContasEditarConta;
    private javax.swing.JComboBox<String> jComboBoxReceitasCadastroConta;
    private javax.swing.JComboBox<String> jComboBoxReceitasEdicaoReceita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField jTextFieldContasCadastrarCpf;
    private javax.swing.JTextField jTextFieldContasCadastrarTitular;
    private javax.swing.JTextField jTextFieldContasEditarCpf;
    private javax.swing.JTextField jTextFieldContasEditarSaldo;
    private javax.swing.JTextField jTextFieldContasEditarTitular;
    private javax.swing.JTextField jTextFieldReceitasCadastroDataEdicaoEsperado;
    private javax.swing.JTextField jTextFieldReceitasCadastroDataRecebimento;
    private javax.swing.JTextField jTextFieldReceitasCadastroDataRecebimentoEsperado;
    private javax.swing.JTextField jTextFieldReceitasCadastroDescricao;
    private javax.swing.JTextField jTextFieldReceitasCadastroValor;
    private javax.swing.JTextField jTextFieldReceitasEdicaoDataRecebimento;
    private javax.swing.JTextField jTextFieldReceitasEdicaoDescricao;
    private javax.swing.JTextField jTextFieldReceitasEdicaoValor;
    // End of variables declaration//GEN-END:variables
}
